apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: my-namespace
spec:
  containers:
    - image: tanvn84/kubia
      name: kubia
      ports:
      - containerPort: 8080
        protocol: TCP
