apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: tanvn84/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /healthCheck
        port: 8080
      initialDelaySeconds: 15
